### ISSUE TITLE
hardlink is not supported

### ISSUE THREAD

**Issue by siddontang** [osrg/hookfs#10]
Hi @AkihiroSuda 

If we use hardlink, the error `Function not implemented` raises, maybe we should support hardlink.

Like:

```go
pathFsOpts := &pathfs.PathNodeFsOptions{ClientInodes: true}
pathFs := pathfs.NewPathNodeFs(hookfs, pathFsOpts)
```

Do you prefer supporting hardlink by default or use a configuration?

**Comment by AkihiroSuda** [comment]
+1 for supporting by default
